### ISSUE TITLE
[Question] ZF2 support

### ISSUE THREAD

**Issue by tonivdv** [mikemix/TacticianModule#12]
Hi @mikemix ,

I was wondering, if I would provide a new PR for an update on the 1.2 version (compatible with ZF2) would you accept it? 

For example we are using InvokeInflector and we have to manually add it to the invokables because it's missing in the modules module.config.php file.

Let me know before I fork and maintain compatibility myself.

Cheers

**Comment by tonivdv** [comment]
Hi @mikemix ,

Since I posted this on the day github had major issues, maybe the notification didn't come your way.

If you could provide some feedback in order to know whether or not I should continue on our fork for zf2 compatibility ?!

Many thanks

Cheers

**Comment by mikemix** [comment]
Due to lack of spare time I do not maintain this library anymore. I switched to Symfony some time ago anyway.

**Comment by tonivdv** [comment]
@mikemix I understand both reasons :) We are using both technologies. Do you want to give the module for adoption, or you keep it and we simply continue with our fork?

**Comment by tonivdv** [comment]
Fixed in #13 . And as discussed in the PR, master is compatible with ZF2 which I ignored due to internal issues on our side.

**Comment by snapshotpl** [comment]
Master is not compatible with ZF2. Your are welcome to can add (again) support to zf2. There isn't any feature that require only zf3, however it complicate a little code. @tonivdv maybe better to update your project to zf3? My experience says that update make app faster 5%-10%.

**Comment by tonivdv** [comment]
@snapshotpl Of course, it's on our todo to upgrade it, but we have some legacy stuff that requires a lot of deprecation removals etc ... long story short impossible to do in a short period of time.

But thank you for specifying it's not zf2 compatible. This is also why I proposed to create a new 1.2 release here. Basically temporary branching from latest 1.2 release, merge it, and recreate a release ... What do you think?

**Comment by snapshotpl** [comment]
@tonivdv sounds good. Prepare please PR, I will review and release all things.

**Comment by tonivdv** [comment]
@snapshotpl could do that, but only if the branch 2.0 is created first no? Otherwise the PR will point to master which will tell me nothing changed ... :/

**Comment by snapshotpl** [comment]
@tonivdv start from https://github.com/mikemix/TacticianModule/releases/tag/1.2.2 and cherry-pick your last commit from v2

**Comment by tonivdv** [comment]
@snapshotpl That I know, but when pushing a PR to you I need to choose a destination branch. Since master has already that fix I can't use that (logic), so reason why I requested a branch from latest 1.2 tag. Unless I'm missing a github feature there is not other way to provide a PR. 

I currently created PR #14 with target branch "changes" but not sure what that branch stands for!

**Comment by tonivdv** [comment]
@snapshotpl Do you have some time to check this? Thanks.

**Comment by tonivdv** [comment]
@snapshotpl gentle reminder :)
